/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'booklet-notes': BookletNote;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'booklet-notes': BookletNotesSelect<false> | BookletNotesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fa') | ('en' | 'fa')[];
  globals: {
    'site-content': SiteContent;
  };
  globalsSelect: {
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
  };
  locale: 'en' | 'fa';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  section?: ('hero' | 'arvin' | 'aida' | 'gallery') | null;
  /**
   * CSS object-position value, e.g. "50% 20%"
   */
  focalPosition?: string | null;
  /**
   * Lower numbers appear first in the gallery grid
   */
  gallerySortOrder?: number | null;
  galleryColSpan?: number | null;
  galleryRowSpan?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booklet-notes".
 */
export interface BookletNote {
  id: string;
  name: string;
  relation?: string | null;
  message: string;
  /**
   * Uncheck to hide a note from the public memorial booklet
   */
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'booklet-notes';
        value: string | BookletNote;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  section?: T;
  focalPosition?: T;
  gallerySortOrder?: T;
  galleryColSpan?: T;
  galleryRowSpan?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booklet-notes_select".
 */
export interface BookletNotesSelect<T extends boolean = true> {
  name?: T;
  relation?: T;
  message?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: string;
  nav: {
    brand: string;
    navAbout?: string | null;
    navGallery?: string | null;
    navMemory?: string | null;
    navNews?: string | null;
    navCta?: string | null;
  };
  hero?: {
    heroKicker?: string | null;
    heroTitle?: string | null;
    heroDates?: string | null;
    heroIntro?: string | null;
    heroCta1?: string | null;
    heroCta2?: string | null;
  };
  about?: {
    aboutKicker?: string | null;
    aboutTitle?: string | null;
    aboutIntro?: string | null;
    arvinName?: string | null;
    arvinBio?: string | null;
    aidaName?: string | null;
    aidaBio?: string | null;
    aboutLoss?: string | null;
  };
  gallery?: {
    galleryKicker?: string | null;
    galleryTitle?: string | null;
  };
  memory?: {
    memoryKicker?: string | null;
    memoryTitle?: string | null;
    memoryIntro?: string | null;
    card1Tag?: string | null;
    card1Title?: string | null;
    card1Body?: string | null;
    instagram?: string | null;
    facebook?: string | null;
    card2Tag?: string | null;
    card2Title?: string | null;
    card2Body?: string | null;
    card2Cta?: string | null;
    card3Tag?: string | null;
    card3Title?: string | null;
    card3Body?: string | null;
    card3Cta?: string | null;
    card4Tag?: string | null;
    card4Title?: string | null;
    card4Body?: string | null;
    card4Cta?: string | null;
    card5Tag?: string | null;
    card5Title?: string | null;
    card5Body?: string | null;
    card5Cta1?: string | null;
    card5Cta2?: string | null;
  };
  booklet?: {
    bookletTag?: string | null;
    bookletTitle?: string | null;
    bookletSubtitle?: string | null;
    labelName?: string | null;
    placeholderName?: string | null;
    labelRelation?: string | null;
    placeholderRelation?: string | null;
    labelMessage?: string | null;
    placeholderMessage?: string | null;
    submitLabel?: string | null;
    submitLabelDone?: string | null;
    thanks?: string | null;
  };
  news?: {
    newsKicker?: string | null;
    newsTitle?: string | null;
    items?:
      | {
          tag?: string | null;
          date?: string | null;
          title?: string | null;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    contactTag1?: string | null;
    contactEtsLine?: string | null;
    contactEtsContribute?: string | null;
    contactEtsQuestions?: string | null;
    contactTag2?: string | null;
    contactAssocContact?: string | null;
    contactAssocFacebook?: string | null;
    contactAssocDonate?: string | null;
  };
  footer?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        brand?: T;
        navAbout?: T;
        navGallery?: T;
        navMemory?: T;
        navNews?: T;
        navCta?: T;
      };
  hero?:
    | T
    | {
        heroKicker?: T;
        heroTitle?: T;
        heroDates?: T;
        heroIntro?: T;
        heroCta1?: T;
        heroCta2?: T;
      };
  about?:
    | T
    | {
        aboutKicker?: T;
        aboutTitle?: T;
        aboutIntro?: T;
        arvinName?: T;
        arvinBio?: T;
        aidaName?: T;
        aidaBio?: T;
        aboutLoss?: T;
      };
  gallery?:
    | T
    | {
        galleryKicker?: T;
        galleryTitle?: T;
      };
  memory?:
    | T
    | {
        memoryKicker?: T;
        memoryTitle?: T;
        memoryIntro?: T;
        card1Tag?: T;
        card1Title?: T;
        card1Body?: T;
        instagram?: T;
        facebook?: T;
        card2Tag?: T;
        card2Title?: T;
        card2Body?: T;
        card2Cta?: T;
        card3Tag?: T;
        card3Title?: T;
        card3Body?: T;
        card3Cta?: T;
        card4Tag?: T;
        card4Title?: T;
        card4Body?: T;
        card4Cta?: T;
        card5Tag?: T;
        card5Title?: T;
        card5Body?: T;
        card5Cta1?: T;
        card5Cta2?: T;
      };
  booklet?:
    | T
    | {
        bookletTag?: T;
        bookletTitle?: T;
        bookletSubtitle?: T;
        labelName?: T;
        placeholderName?: T;
        labelRelation?: T;
        placeholderRelation?: T;
        labelMessage?: T;
        placeholderMessage?: T;
        submitLabel?: T;
        submitLabelDone?: T;
        thanks?: T;
      };
  news?:
    | T
    | {
        newsKicker?: T;
        newsTitle?: T;
        items?:
          | T
          | {
              tag?: T;
              date?: T;
              title?: T;
              body?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        contactTag1?: T;
        contactEtsLine?: T;
        contactEtsContribute?: T;
        contactEtsQuestions?: T;
        contactTag2?: T;
        contactAssocContact?: T;
        contactAssocFacebook?: T;
        contactAssocDonate?: T;
      };
  footer?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}